### ISSUE TITLE
Configure Traefik to support azure as DNS provider

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#116]
This should be part of Azure DNS integration. But instances ar enot loading over https.

## Acceptance Criteria

- [ ] https://a-ckan-instance.viderum.xyz/ is working

**Comment by pwalsh** [comment]
@zelima can you please write a story and acceptance criteria (I assumed this was working with the Azure DNS integration that is done)

**Comment by zelima** [comment]
I assumed that way as well, but it is not. Pulled out separately to track...

**Comment by zelima** [comment]
This is now part of #93
