### ISSUE TITLE
Internal server error with the "Datasets" button

### ISSUE THREAD

**Issue by developper-ing** [datopian/ckan-cloud-operator#117]
Hello,
I configure **CKAN 2.8.2** under  **Ubuntu 16.04**. I Launched the different commands to obtain the dashobard of CKAN (ckan db init, start apache2, start nginx, start jetty8) and I checked the status of each of them. It was OK (activate)
I create a profile, but on  cliking the **"Datasets" button** , an **internal error server message appeared**.
I'am a beginner with CKAN I don't know what is the source of error.
I attached you a sceenshot about the error display :
![internal error server](https://user-images.githubusercontent.com/49305014/73460849-76b68b80-4379-11ea-9c2e-b0d8714bc7c9.JPG)

**Comment by pwalsh** [comment]
Hi. You are on the wrong issue tracker. Please try https://gitter.im/ckan/chat for help
