### ISSUE TITLE
Not all envvars are set correctly when creating from-google-envvars

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#17]
While this works fine for some instances, I've just got an error from migrating `meerbusch`

```
  File "/home/zelima/datopian/viderum/ckan-cloud-operator/ckan_cloud_operator/deis_ckan/envvars.py", line 68, in _update
    for k, v in envvars.items()}}
  File "/home/zelima/datopian/viderum/ckan-cloud-operator/ckan_cloud_operator/deis_ckan/envvars.py", line 68, in <dictcomp>
    for k, v in envvars.items()}}
AttributeError: 'NoneType' object has no attribute 'encode'
```

Looking at the values of the `envvars` I've got unexpected database URLs:

```
'CKAN_SQLALCHEMY_URL': 'postgresql://meerbusch:None@*.*.*.*:****/meerbusch',
'CKAN__DATAPUSHER__URL': None,
'CKAN__DATASTORE__READ_URL': 'postgresql://None:None@*.*.*.*:****/meerbusch-datastore',
'CKAN__DATASTORE__WRITE_URL': 'postgresql://meerbusch-datastore:None@*.*.*.*:****/meerbusch-datastore'
etc...
```
Note
- CKAN_SQLALCHEMY_URL: passowrd in None
- CKAN__DATAPUSHER__URL: is None
- CKAN__DATASTORE__READ_URL: both user and password is None

---

Original `CKAN__DATAPUSHER__URL` looks like this https://datapusher-de.l3.ckan.io/.  Usually, they look like this https://datapusher-1.ckan.io/

The script can't pass this line https://github.com/ViderumGlobal/ckan-cloud-operator/blob/master/ckan_cloud_operator/deis_ckan/datapusher.py#L16

```
routes = kubectl.get(
                f'CkanCloudRoute -l ckan-cloud/datapusher-name={datapusher_name},ckan-cloud/route-type=datapusher-subdomain',
                required=False
            )
```

`routes` look like this if I print 
```
{'apiVersion': 'v1', 'items': [], 'kind': 'List', 'metadata': {'resourceVersion': '', 'selfLink': ''}}
```

**Comment by OriHoch** [comment]
fixed on master

**Comment by zelima** [comment]
Datapusher urls are fixed but, I'm still getting None@None on production. Will try to fix.

Seems like annotations problems:
```
old deployment generation = 2
Activated service account credentials for: [ckan-cloud-operator-production@ckan-cloud.iam.gserviceaccount.com]
Updated property [compute/zone].
Error from server (NotFound): secrets "lincolnshire-annotations" not found
```
We are getting datastore user and passwords from there: https://github.com/ViderumGlobal/ckan-cloud-operator/blob/master/ckan_cloud_operator/deis_ckan/envvars.py#L29-L31

**Comment by zelima** [comment]
Manually deleted databases and recreated. No everything looks fine. Think we can close as FIXED

**Comment by zelima** [comment]
Did not repeat since, closing as FIXED
