### ISSUE TITLE
[task] ckan instance manual testing and load testing

### ISSUE THREAD

**Issue by OriHoch** [datopian/ckan-cloud-operator#29]
This issue is a task which could be performed in parallel for multiple instances.

All testing should be done on production ckan-cloud environment.

## Migrate an instance

This step should run by a ckan-cloud developer which has ckan-cloud-operator installed and configured locally.

start the gcloud sql proxy locally -

```
ckan-cloud-operator ckan-infra cloudsql-proxy
```

keep running in background, and in a new terminal - 

set env var to use the proxy and migrate an instance - 

```
export CKAN_CLOUD_OPERATOR_USE_PROXY=yes

ckan-cloud-operator deis-instance migrate OLD_SITE_ID NEW_INSTANCE_ID ROUTER_NAME
```

* OLD_SITE_ID - The old cluster site ID of the instance to migrate
* NEW_INSTASNCE_ID - The new cluster instance ID (usually the same as OLD_SITE_ID)
* ROUTER_NAME - New cluster router name that will be used to route external traffic (usually `production-1`)

If the migration fails, re-run the migrate command until it works and be patient as it could take some time for instance to be fully migrated and working.

Wait for the site to be online and make sure datasets are displayed:

https://cc-p-NEW_INSTANCE_ID.ckan.io/

## Test an instance

This step could be done without prior knowledge about ckan-cloud or ckan-cloud-operator

Browse through the instance datasets, groups and organizations and verify that there are not broken images or error pages.

Log-in to the relevant CKAN instance with admin username/password

**important** check the browser URL after log-in to make sure you are logged-in to the relevant testing instance

With a logged-in admin account:
* Add a group, organization, private and public dataset, make sure they are displayed properly.
  * Fill-in as many fields as possible, upload an image, etc..
* Look for additional modules / options and validate them
* Search for the group/organization/datasets, ensure they are returned in search results.

Log-out and verify the site and created resources with an anonymous account:
* Search for the group/organization/datasets, ensure they are returned in search results.
* Look for additional modules / options and validate them

Log-in and deleted the created resources:
* Delete the created group, organization and datasets
* make sure they are deleted properly.

## Load test an instance

* Log-in to [Octoperf](https://app.octoperf.com)
* Add a new project: `cc-p-INSTANCE_ID`
    * Create by Website or Rest API
    * Static Website
    * Paste URLs to the instance homepage, groups, organizations, datasets
    * enable - parse response to extract subpages
* Create VU
* set scenario settings
* Create Scenario
* Run scenario

**Comment by OriHoch** [comment]
completed task for instance ori-test-vrr

![image](https://user-images.githubusercontent.com/1198854/52273862-b9ef4180-2953-11e9-8295-fdbb35fe86bc.png)

**Comment by zelima** [comment]
The result of load testing on the old cluster:

- 2 instances in parallel (https://old.datahub.io/ and https://us-ed.l3.ckan.io/), 50 concurrent users for 10 minutes
  - Errors: 0
  - ~8000 hits total
  -  average response time ~5sec
  - max response time 15sec
- 3instances in parallel (https://lincolnshire.l3.ckan.io,  https://data.nav.no/ and https://montreal.l3.ckan.io/), 50 concurrent users for 20 minutes
  - Errors: 5
  - ~30000 hits total
  -  average response time ~6-7 sec
  - max response time 17sec

Pretty much similar to edge cluster

**Comment by zelima** [comment]
### Edge cluster

Here you can find the results of load and manual testing https://docs.google.com/spreadsheets/d/1K3721rhM4b14KwcQoznq4ijnYKNtExXSoVPZb35JYZo/edit#gid=1825672970

Also, see on octoperth https://app.octoperf.com/#/app/workspace/AWio9Oe8oNkppeW4cila/projects

We have tested the following web endpoints:

/
/dataset
/organization
/group
and subpages of all above
Most of the instances went fine here are some with problems:

https://cc-e-ni.ckan.io/ - 922 errors 503 - service unavailable
https://cc-e-inverness.ckan.io/ - 449 errors 404 - not found (problem with https://site_url/en_GB endpoints)
https://cc-e-panama.ckan.io/ - 8500 errors 502 Bad Gateway
https://cc-e-perth.ckan.io/ - 481 errors 404 - not found (problem with https://site_url/en_GB endpoints)
https://cc-e-us-ed.ckan.io/ - 319 errors 500 Internal Server Error
Load testing was done twice with different configurations.

Max 10 users for 10 minutes
Max 50 users for 20 minutes (max available for free plan)
One significant difference between the first and second tests is that average and max response time has increased from ~0.5 seconds to ~7 seconds
