### ISSUE TITLE
delete does not delete databases

### ISSUE THREAD

**Issue by zelima** [datopian/ckan-cloud-operator#6]
`ckan-cloud-operator deis-instance delete --force aridhia-staging` fails to remove databases. Looking at the logs: 

```
 ERROR:  must be owner of database aridhia-staging E 
 STATEMENT:  DROP DATABASE IF EXISTS "aridhia-staging" I 
```

**Comment by OriHoch** [comment]
fixed, using psql to delete databases instead of via gcloud
