### ISSUE TITLE
How does Deis fit into the platform? 

### ISSUE THREAD

**Issue by jqnatividad** [datopian/ckan-cloud-operator#64]
@aluminiumgeek @akariv 

Asking in behalf of @adborden in reference to 

https://github.com/datopian/ckan-cloud-operator/blob/full-documentation/docs/DOCUMENTATION.md#devops-giude

**Comment by pwalsh** [comment]
@jqnatividad

The early versions of CKAN Cloud Operator ran with support for [Deis Workflow](https://github.com/deis/workflow). Some of the code still supports Dockerfiles that were designed with that deployment target.
