### ISSUE TITLE
Running CCO on "minikube"

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckan-cloud-operator#68]
# Job story

When I use and interact with CKAN Cloud Operator (CCO), I want to be able to run it in local development, so I can debug and develop the codebase and running CKANs in it without standing up a whole cluster on a major cloud provider.

# Context

Currently, we have a range of manual steps that are under- or un-documented, to run CKAN Cloud. And, the assumption is that one is deploying onto a public cloud (GCP, AWS, Azure). This creates friction for both new users (who want to run the thing and see if it addresses their needs), and for DevOps team members already running CCO to manage clusters of CKAN (who need an easier way to standup clusters for testing, debugging, and development purposes).

# Acceptance criteria

- [ ] "Getting stared with CKAN Cloud" documentation that takes me from a terminal, to having CKAN Cloud Operator running on minikube on my local development machine
  - [ ] I can execute basic CCO commands
  - [ ] I can move on to next steps in documentation to deploy a CKAN instance into my setup
- [ ] Any supporting code changes to run a working cluster on minikube

# Note:
"Minikube" is not a strict requirement - any local kubernetes system could work.
We should choose one supported (free) local k8s flavor which is supported on most operating systems, and make sure documentation also includes links to installation instructions for that selected solution.

**Comment by zelima** [comment]
To update with progress

- Was having hard times with starting minkube properly (now solved) https://github.com/ViderumGlobal/ckan-cloud-helm/issues/9
- Was trying to deploy ckan instance without centralized infra analysis here https://github.com/ViderumGlobal/ckan-cloud-helm/issues/10
- After discussed with @akariv switched to centralized infra. Deployed successfully but having troubles with ckan and centralized db communication. Currently debugging, the analysis here  https://github.com/ViderumGlobal/ckan-cloud-helm/issues/9

**Comment by kimwdavidson** [comment]
Lower priority. Esteban and Paul to discuss

**Comment by estebanruseler** [comment]
Moving this to icebox as per discussion with Aaron as this task performed by Irakli is not in the GSA project.
