### ISSUE TITLE
Create (versioned) image for CCO and its direct dependencies

### ISSUE THREAD

**Issue by pwalsh** [datopian/ckan-cloud-operator#82]
# Story

When I administer a CCO-managed cluster, I want to ensure that CCO is built correctly, with a known version, and deployed in a deterministic way, so that I can manage CCO changes and security updates and quickly incorporate them into a running cluster via immutable deployment.

As an operator, I want the CCO management server to be provisioned from an image using an automated build process so that any changes or security updates are quickly incorporated into the running instance via immutable deploy.

# Context

We want to be able to deploy a know working bundle of CCO and its dependencies, tagged to a version, to any CKAN Cloud infrastructure.

# Acceptance criteria

- [ ] Docker image that bundles a tagged version of CCO and any direct dependencies (i.e.: Jenkins)
- [ ] CI/CD for building this docker image
  - [ ] Ensure core linting and testing on each build
- [ ] Integration with the terraform templates that standup infrastructure, so that the "CCO management server" is deployed as part of that process
- [ ] Documentation on preferred use of the CCO in this way

**Comment by adborden** [comment]
@pwalsh so should we close https://github.com/GSA/datagov-ckan-multi/issues/189 as a duplicate?

**Comment by pwalsh** [comment]
@adborden if that works for you, then would be great to track it here on this repo, so yes.

**Comment by kimwdavidson** [comment]
@akariv could you put an estimate on this ticket?

**Comment by akariv** [comment]
It will be done by end of this week.

**Comment by kimwdavidson** [comment]
@estebanruseler to determine status with @akariv
