### ISSUE TITLE
Automate provisioning of CCO managed clusters

### ISSUE THREAD

**Issue by kimwdavidson** [datopian/ckan-cloud-operator#84]

**Comment by pwalsh** [comment]
@kimwdavidson @estebanruseler 

Based on the title, this is a duplicate of https://github.com/datopian/ckan-cloud-operator/issues/69

I suggest we close it.

**Comment by adborden** [comment]
This is the epic issue (in ZenHub) which tracks all the smaller issues, like #69, so not a duplicate.

But, we should probably close https://github.com/GSA/datagov-ckan-multi/issues/184, whose name is a bit general.

**Comment by pwalsh** [comment]
@adborden ok. maybe if this the epic then we move it onto the datagov-ckan-multi tracker then? As it is now, it doesnt provide any info that is usable on this issue tracker. But, I am happy with whatever you @kimwdavidson and @estebanruseler would like.

**Comment by adborden** [comment]
Okay, lets update https://github.com/GSA/datagov-ckan-multi/issues/184 to be the epic issue for this.

**Comment by adborden** [comment]
Hmm, I'm having trouble adding datopian issues to the GSA epic... ZenHub doesn't give an error, but it seems the assignment doesn't stick. Maybe @kimwdavidson that's why you opened this issue?

**Comment by kimwdavidson** [comment]
Closing
